sudo: required
branches:
  only:
    - master
    - release
dist: trusty
language: python
python:
- '3.6'
before_install:
- sudo add-apt-repository ppa:koffeinflummi/armake -y
- sudo apt-get update -qq
- sudo apt-get install armake -y
- make --version
- armake --version
install: true
before_script:
  - if [ -n "${GH_TOKEN}" ] && [ "${TRAVIS_BRANCH}" == "master" ] && [ "${TRAVIS_PULL_REQUEST}" == "false" ]; then
      pip install pygithub;
      pip install pygithub3;
    fi
script:
  - make -j 3
  - python3 tools/sqf_validator.py
  - python3 tools/config_style_checker.py
  - if [ -n "${GH_TOKEN}" ] && [ "${TRAVIS_BRANCH}" == "master" ] && [ "${TRAVIS_PULL_REQUEST}" == "false" ]; then
      python3 tools/deploy.py;
    fi
env:
  global:
  - secure: E6FCH4pVIbA+pphLewjqQFO37ZjwNdz4m+dGlHlCutkB6PxY79BzpzfTwQol5jNn9/p4Hy5k+xefFx5eXBEHTxRPy7mAE00bMX1tSMEJZTeonQBIDQ4wYtJMAEmAEj76n+cGZMDxs4a/Q6bMXQlabJ591aoCpkgAi1Kj+UQfqmR0ee9MA43bZxrEiRqHhknyKM3Va6KRvuUOr+vyTuCshndLVk9WxcS7pVfrH43cgCL/swbvUAhZdk6hqzuHtGtSOHgoZU7AdSxxiV9DoBk7iq465LrqxqFC5Tv1WyKdElk5waHLwTPVk6tf9kbL6mpB0CW/vzzJjD/xEeaUajxsAnKP+fWWuCmp9b5n7GWtje+5PI3meott5iTLT5daqJa1R97UtErF/h8ZI+TIjyD0Dh05uG3XK0I+zNBQDJwvOvQxqE975fcPo8XXu6GxDMD6aRHINEpbvfbHQ4XeHTpvA3Zw1ng+3Um75qPhWVTpHEUDvAaqGIdtugzBfj3SyA94kb8Rq4PsKm2HF8poR5mAUCTXutYZiBA1eAr+eVuvjpRZxr2TvMr7gDQs5pHwdQq8Vcaun/VNpA4hCRiVP1bQ/mt3mfWGPQkhijITVbo6mQ9bW5ef78xDkLTv9y5tg67GWSO6gH3OV4MzaKlIcWWqg0Nz05J8kgq8M0S91DS32GE=
notifications:
  email:
    on_success: never
    on_failure: change
